version: '3'
services:
  api:
    build: MonitoringApi
    ports:
      - "5000:80"
    cpu_count: 1
    domainname: monitor-target

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    
  prometheus:
    image: bitnami/prometheus
    ports:
      - "4000:9090"
