global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'localhost:5000'

